### ISSUE TITLE
/tags/TAG?wofid=WOFID should be /tags/TAG/WOFID

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-api#106]
https://places.mapzen.com/tags/korean/?wofid=1108912387

**Comment by dphiffer** [comment]
Is `https://places.mapzen.com/tags/korean/in-1108912387` okay? I went with that based on #92.

**Comment by thisisaaronland** [comment]
Ah, that's fine. You can close this assuming all the links, etc. are up to date.

**Comment by dphiffer** [comment]
There's one link that isn't updated. I'll close it after the next deploy.
