### ISSUE TITLE
Unable to bundle descendants of Earth

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www-api#45]
https://whosonfirst.mapzen.com/spelunker/download/0/#0/-0/0

When trying to download a bundle of records that are descendants of Earth, the descender tool is unable to create a GeoJSON collection or CSV summary. The following error is given:

`Error: Missing 'id' parameter (432)`

Command that will illustrate the error:

```
curl -X GET 'https://whosonfirst-api.mapzen.com?method=whosonfirst.places.getDescendants&api_key=mapzen-xxxxxx&id=0&format=json'
```

**Related**: https://github.com/whosonfirst-data/whosonfirst-data/issues/811

**Comment by thisisaaronland** [comment]
I know what the problem is here but it does beg the question of whether it should even be _possible_ to do this, because it represents a prohibitive strain on the databases.

What are you trying to fetch exactly, besides "everything" ?

**Comment by dphiffer** [comment]
![:earth_americas:](https://media.giphy.com/media/14kdiJUblbWBXy/giphy.gif)

**Comment by stepps00** [comment]
I need to grab a feature collection of any descendant record of Earth (record with `"earth_id"` in the `wof:hierarchy` property) for a wof-data issue (whosonfirst-data/whosonfirst-data#811), which should be about 3,000 records. 

I'm able to `grep` the repo locally to collect ids, so I have a work-around. I doubt this will be a frequent task; leaving this behavior in it fine by me.
