### ISSUE TITLE
Teach getHierarchiesByLatLon to return standard "get info" blobs

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-api#47]
Add a flag/parameter to `getHierarchiesByLatLon` and get back something like this :

```
{
     "PLACETYPE": { STANDARD GET INFO PLACE BLOB PLUS EXTRAS HOOHAH },
     "PLACETYPE": { STANDARD GET INFO PLACE BLOB ... },
     ... and so on ...
}
```

Where the standard info response looks like:

```
{
      "wof:id": 85688637,
      "wof:parent_id": "85633793",
      "wof:name": "California",
      "wof:placetype": "region",
      "wof:country": "US",
      "wof:repo": "whosonfirst-data"
}
```

Under the hood, this is basically just a question of invoking the same code that we're using for `getInfoMulti`.

**Comment by simonw** [comment]
Fantastic, this is exactly what we needed! Thanks very much.
