### ISSUE TITLE
allow multiple placetypes in whosonfirst.places.search

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst/whosonfirst-www-api#5]
a comma delimited list allowing multiple `placetypes` would be handy, especially for higher level things like countries and regions

**Comment by thisisaaronland** [comment]
This was added recently. Multiple placetypes are passed in as a `;` separated list. There is also a sibling `exclude_placetype` parameter.

https://whosonfirst-api.mapzen.com/?method=whosonfirst.places.search&api_key=mapzen-xxxxxx&exclude_placetype=venue;neighbourhood&iso=CA&name=valley&format=json
