### ISSUE TITLE
placetype=locality filter on getNearby for New York coordinate returns empty list

### ISSUE THREAD

**Issue by wsusanto-eb** [whosonfirst/whosonfirst-www-api#70]
https://whosonfirst-api.mapzen.com/?api_key=mapzen-XXXXX&method=whosonfirst.places.getNearby&latitude=40.7127837&longitude=-74.0059413&placetype=locality&radius=80467

```
 {
    "places": [],
    "next_query": null,
    "total": null,
    "page": null,
    "per_page": 100,
    "pages": null,
    "cursor": null,
    "stat": "ok"
}
```

That's this point here: https://www.google.com/maps/search/40.7127837,-74.0059413
![image](https://user-images.githubusercontent.com/3357867/29100147-b0eb9b0e-7c5e-11e7-93d0-1e0a8d0e13ae.png)

**Comment by thisisaaronland** [comment]
Yeah, I can reproduce this. Investigating...

**Comment by thisisaaronland** [comment]
This appears to have been an indexing hiccup. Your immediate query results stuff within the immediate vicinity but I will leave this ticket open until the re-indexing is complete. Apologies for the confusion.

```
curl -X GET 'https://whosonfirst-api.mapzen.com?method=whosonfirst.places.getNearby&api_key=mapzen-xxxxxx&latitude=40.7127837&longitude=-74.0059413&placetype=locality&format=json'

{
  "places": [
    {
      "wof:id": 85977539,
      "wof:parent_id": -4,
      "wof:name": "New York",
      "wof:placetype": "locality",
      "wof:country": "US",
      "wof:repo": "whosonfirst-data"
    }
  ],
  "next_query": null,
  "total": null,
  "page": null,
  "per_page": 100,
  "pages": null,
  "cursor": null,
  "stat": "ok"
}
```

**Comment by thisisaaronland** [comment]
Re-indexing is complete and your query returns many localities!
