### ISSUE TITLE
Autocomplete with sources=wof does not apply focus.point

### ISSUE THREAD

**Issue by wsusanto-eb** [whosonfirst/whosonfirst-www-api#73]
Text: madison

Focus point: New York
https://search.mapzen.com/v1/autocomplete?api_key=mapzen-XXXXXXX&focus.point.lat=40.712&focus.point.lon=-74.005&text=madison&sources=wof&layers=locality
```
Madison, WI, USA
Madison, AL, USA
Madison, NJ, USA
Madison Heights, VA, USA
Fort Madison, IA, USA
```

Focus point: San Francisco
https://search.mapzen.com/v1/autocomplete?api_key=mapzen-XXXXXXX&focus.point.lat=37.774&focus.point.lon=-122.419&text=madison&sources=wof&layers=locality
```
Madison, WI, USA
Madison, AL, USA
Madison, NJ, USA
Madison Heights, VA, USA
Fort Madison, IA, USA
```

Both New York and San Francisco return the same list with the same order.
Expected nearby results on the top of the list when focus.point.lat and focus.point.lon parameters are provided.
https://mapzen.com/documentation/search/autocomplete/#global-scope-local-focus

**Comment by thisisaaronland** [comment]
Hi,

This is an issue with `Pelias` the MZ search rather than Who's On First, specifically. It should be reported here: https://github.com/pelias/pelias/issues
