### ISSUE TITLE
Ensure 'extras' for things coming out of Tile38

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/whosonfirst-www-api#8]
Related: issue #3

**Comment by thisisaaronland** [comment]
The code is in place but still requires hooks to signal that a Tile38 record needs to fetch details from ES.

**Comment by migurski** [comment]
I’m unable to get `gn:population` out via the `extras` parameters — is this why? [Here is a sample request URL](https://whosonfirst-api.dev.mapzen.com/?method=whosonfirst.places.getIntersects&min_latitude=28.8071692&max_latitude=29.5987236&min_longitude=-95.8713406&max_longitude=-95.0582461&extras=gn:population,geom:latitude,geom:longitude&placetype=locality). Galveston (WoF ID 101724261) [does have a population defined](https://whosonfirst.mapzen.com/data/101/724/261/101724261.geojson).

**Comment by thisisaaronland** [comment]
Correct – you are unable to get `gn:population` because this ticket hasn't been resolved. We might as well stress-test things with whatever you're doing so I can add that shortly.

**Comment by thisisaaronland** [comment]
Fixed with https://github.com/whosonfirst/whosonfirst-www-api/commit/11e89129c5ec77a241f2f9d9fee9cda376a72287
